### ISSUE TITLE
Node Issues (Again. 😔 )

### ISSUE THREAD

**Issue by Goman60** [GO-Technologies/DPATL#8]
Not being able to have more than one type of a node in a file. 
### Please help!
@VelocityDesign

**Comment by VelocityDesign** [comment]
Ok, is this an issue after Python support was implemented?

**Comment by Goman60** [comment]
@VelocityDesign No, the bug showed up in the Beta 1, I just thought I had fixed it. I was wrong. lol

**Comment by Goman60** [comment]
Bump! Update: the problem lies in the get_string_between() function I think. Maybe looping the ini()?

**Comment by VelocityDesign** [comment]
For a sec I thought that someone else was helping!

**Comment by Goman60** [comment]
@VelocityDesign 😂. But sad though.

**Comment by Goman60** [comment]
Development: The problem may be fixed in the next beta by switching to on the fly regex.

**Comment by Goman60** [comment]
Python node issues have been fixed. All languages will support multiple nodes in v0.5

**Comment by Goman60** [comment]
Update: Loading python modules asynchronously results in an unresolved promise. This will be fixed, but is a delay.

**Comment by Goman60** [comment]
My web host is down so I can not work on DPATL for about a month. 😞
